markdown: kramdown
permalink: /:title/
url: https://rice4dome.github.io/riceAS.github.io/
name: ricePSP
author: Weizhi Ouyang
email: wzouyang2@126.com 
highlighter: rouge
safe: true
paginate: 20
about: "A comprehensive database of rice phase separation-associated proteins"
