markdown: kramdown
permalink: /:title/
url: https://rice4dome.github.io/riceAS.github.io/
name: ricePSP
author: Weizhi Ouyang
qq: 1481758069
email: venyao@qq.com 
github: venyao
highlighter: rouge
safe: true
paginate: 20
about: "A comprehensive database of rice phase separation-associated proteins"
