markdown: kramdown
permalink: /:title/
url: https://riceas.github.io/
name: ricePSP
author: Wen Yao (姚文)
qq: 1481758069
email: venyao@qq.com 
github: venyao
highlighter: rouge
safe: true
paginate: 20
about: "A comprehensive database of rice phase separation-associated proteins"
